import{a as L,S as b,i as d}from"./assets/vendor-BIn0hBn5.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))i(o);new MutationObserver(o=>{for(const t of o)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function n(o){const t={};return o.integrity&&(t.integrity=o.integrity),o.referrerPolicy&&(t.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?t.credentials="include":o.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(o){if(o.ep)return;o.ep=!0;const t=n(o);fetch(o.href,t)}})();const f="https://pixabay.com/api/",w="50891107-566f278151ee6a9d75cddbbab";async function m(e,r=1,n=15){const i={key:w,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:n};return`${f}${new URLSearchParams(i)}`,(await L.get(f,{params:i})).data}const S=document.querySelector(".gallery");let c;function p(e){const r=e.map(({webformatURL:n,largeImageURL:i,tags:o,likes:t,views:l,comments:y,downloads:g})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${i}">
          <img class="gallery-image" src="${n}" alt="${o}" />
        </a>
        <div class="gallery-info">
          <p><b>Likes:</b> ${t}</p>
          <p><b>Views:</b> ${l}</p>
          <p><b>Comments:</b> ${y}</p>
          <p><b>Downloads:</b> ${g}</p>
        </div>
      </li>
    `).join("");S.insertAdjacentHTML("beforeend",r),c?c.refresh():c=new b(".gallery-link",{captionsData:"alt",captionDelay:250})}const v={position:"topRight",timeout:5e3};d.settings(v);let u=1;const h=15,a={form:document.querySelector(".form"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),input:document.querySelector('input[name="query"]'),loadMoreButton:document.querySelector(".js-load-more")},s={showLoader:()=>a.loader.classList.remove("hidden"),hideLoader:()=>a.loader.classList.add("hidden"),clearGallery:()=>a.gallery.innerHTML="",resetForm:()=>a.input.value="",showError:e=>d.error({message:e}),showInfo:e=>d.info({message:e}),showLoadMore:()=>a.loadMoreButton.classList.remove("hidden"),hideLoadMore:()=>a.loadMoreButton.classList.add("hidden")},E=()=>{const e=a.gallery.querySelector(".gallery-item");if(e){const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}},q=e=>{e.preventDefault();const r=a.input.value.trim();if(!r){s.showError("Please enter search term");return}u=1,P(r)},M=async()=>{u+=1,s.showLoader();try{const e=await m(a.input.value.trim(),u,h);p(e.hits),E(),e.hits.length<h&&(s.hideLoadMore(),s.showInfo("We're sorry, but you've reached the end of search results."))}catch(e){s.showError(`Request failed: ${e.message}`)}finally{s.hideLoader()}},P=e=>{s.showLoader(),s.clearGallery(),s.hideLoadMore(),m(e).then(r=>{if(!r.hits.length){s.showError("No images found. Try another query!");return}p(r.hits),r.totalHits>h&&s.showLoadMore()}).catch(r=>{s.showError(r.message||"Search failed")}).finally(()=>{s.hideLoader()})};a.form.addEventListener("submit",q);a.loadMoreButton.addEventListener("click",M);
//# sourceMappingURL=index.js.map
